### ISSUE TITLE
swagger 格式扩展 

### ISSUE THREAD

**Issue by zzswang** [36node/openapi-ts-gen#6]
## 背景

go swagger 生成的 swagger 文档，和 nestjs 的 swagger 文档有一些差别

现在的 ts-gen 是会报错的，主要是因为格式不兼容

go swagger 生成的文档也是满足 swagger 文档标准的，因此我们需要兼容

## 开发

- 目标 swagger 文档 https://core.tend-uat.36node.com/swagger/index.html
- 能够正确生成 sdk
- sdk 工程是  https://github.com/36node-TenD/core-sdk-ts

**Comment by zzswang** [comment]
sdk 如何生成，可以参考 其它 sdk 工程

**Comment by wangzulong** [comment]
@zzswang 需要https://github.com/36node-TenD/core-sdk-ts的权限，最好有项目的生成sdk的步骤，方便开发调试

**Comment by zzswang** [comment]
参考这个工程

https://github.com/haivivi/pal-sdk-ts

package.json 里有个命令，用来生成 sdk，调用的就是 openapi-ts-gen
